name: trackeat
description: "A new Flutter project for managing account creation and other features."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: ">=2.17.0" # Minimum SDK version to support latest dependencies

# Dependencies required for the application
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  async: 2.11.0
  intl: ^0.19.0
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.4+2
  firebase_core: ^2.25.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.3
  firebase_auth: ^4.17.3
  connectivity_plus: ^6.0.2
  permission_handler: ^11.1.0
  flutter_switch: ^0.3.2

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Add assets here when needed
  assets:
    - assets/images/
    # Example assets (remove or replace these placeholders as needed)
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # Custom fonts configuration (add fonts if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700