name: trackeat
description: "A new Flutter project for managing account creation and other features."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies required for the application
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.5

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Add assets here when needed
  assets:
    # Example assets (remove or replace these placeholders as needed)
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # Custom fonts configuration (add fonts if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700