name: trackeat
description: "A mobile app that helps users track their meals using AI, manage nutrition, and connect with others."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: '>=3.2.0 <4.0.0'  # Updated to latest stable Flutter SDK

# Dependencies required for the application
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_switch: ^0.3.2
  activity_ring: ^0.3.0
  responsive_grid_list: ^1.4.0
  flutter_markdown: ^0.7.0
  image_cropper: ^5.0.1
  path_provider: ^2.1.2
  path: ^1.8.3
  confetti: ^0.7.0

  # State Management
  provider: ^6.1.1

  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.1

  # Device Features
  camera: ^0.11.0+2
  image_picker: ^1.0.7
  speech_to_text: ^7.0.1
  permission_handler: ^11.1.0

  # Storage & Data
  shared_preferences: ^2.3.5

  # Networking & Connectivity
  connectivity_plus: ^6.1.1

  # AI & ML
  google_generative_ai: ^0.4.0

  # Utilities
  intl: ^0.19.0
  async: ^2.11.0

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    
    